{% set name = "tasklib" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tasklib-{{ version }}.tar.gz
  sha256: 5ccd731b52636dd10457a8b8d858cb0d026ffaab1e3e751baf791bf803e37d7b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - backports.zoneinfo

test:
  imports:
    - tasklib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/GothenburgBitFactory/tasklib
  summary: Official Taskwarrior library for Python
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://tasklib.readthedocs.io/

extra:
  recipe-maintainers:
    - jfishe
